# workman-layout
keycode  16 = q
keycode  17 = d
keycode  18 = r
keycode  19 = w
keycode  20 = b
keycode  21 = j
keycode  22 = f
keycode  23 = u
keycode  24 = p
#
keycode  30 = a
keycode  31 = s
keycode  32 = h
keycode  33 = t
keycode  34 = g
keycode  35 = y
keycode  36 = n
keycode  37 = e
keycode  38 = o
keycode  39 = i
#
keycode  44 = z
keycode  45 = x
keycode  46 = m
keycode  47 = c
keycode  48 = v
keycode  49 = k
keycode  50 = l
#
include "compose"
